# Generated by Django 5.0.6 on 2026-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('content', models.TextField(help_text='Rendered as HTML.')),
                ('excerpt', models.CharField(help_text='Short summary shown on the blog listing.', max_length=400)),
                ('author', models.CharField(default='Marco Baldanza', max_length=120)),
                ('pillar', models.CharField(choices=[('networking', 'Wi-Fi & Networking'), ('security', 'Security'), ('development', 'App & Web Development'), ('automation', 'Home Automation'), ('support', 'Support & Maintenance'), ('general', 'General')], default='general', max_length=20)),
                ('meta_description', models.CharField(blank=True, help_text='Used in <meta name=description>. Leave blank to fall back to the excerpt.', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, help_text='Leave blank to keep as a draft. Set a future date to schedule.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
