# Generated by Django 5.0.6 on 2026-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Internal tag identifying which page/CTA the enquiry came from.', max_length=64),
        ),
    ]
