# Generated by Django 5.0.6 on 2026-05-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enterprise_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='audience',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('business', 'Business')], default='', max_length=16),
        ),
    ]
