# Generated by Django 5.2.10 on 2026-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactsubmission_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pillar',
            field=models.CharField(choices=[('networking', 'Wi-Fi & Networking'), ('security', 'Physical Security'), ('development', 'App & Web Development'), ('automation', 'Home Automation'), ('support', 'Support & Maintenance'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
