# Generated by Django 5.2.10 on 2026-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogpost_pillar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('network', 'UniFi Network Engineer'), ('infrastructure', 'Infrastructure Engineer (Cable Installations)')], max_length=32)),
                ('cover_note', models.TextField(blank=True)),
                ('cv_filename', models.CharField(blank=True, max_length=255)),
                ('cv_size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
