# Generated by Django 5.2.10 on 2026-05-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='role',
            field=models.CharField(choices=[('network', 'UniFi Network Engineer'), ('infrastructure', 'Infrastructure Engineer (Cable Installations)'), ('cyber', 'Cyber Security Engineer')], max_length=32),
        ),
    ]
