# Generated by Django 5.2.10 on 2026-06-15 08:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_smart_locks_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.cv_upload_to),
        ),
    ]
