# Generated by Django 5.2.10 on 2026-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_jobapplication_cv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("business", "Business"),
                    ("trade", "Trade / contractor"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("home_small", "Home — under 150 m²"),
                    ("home_medium", "Home — 150–300 m²"),
                    ("home_large", "Home — 300 m² or larger"),
                    ("home_period", "Period or listed home"),
                    ("home_estate", "Estate or multi-building property"),
                    ("business_office", "Business — office"),
                    ("business_retail", "Business — retail / hospitality"),
                    ("business_other", "Business — something else"),
                    ("construction_site", "Construction site / builder's compound"),
                    ("new_build_dev", "New-build development (one or more plots)"),
                    ("other", "Something else"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urgent", "Within 2 weeks"),
                    ("soon", "Within the next month"),
                    ("planned", "1–3 months"),
                    ("phased", "3+ months / phased project"),
                    ("flexible", "Flexible / just exploring"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
