# Generated by Django 5.2.10 on 2026-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_seed_construction_posts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["-published_at", "-created_at"], name="blogpost_pub_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["pillar", "-published_at"], name="blogpost_pillar_pub_idx"
            ),
        ),
    ]
