# Generated by Django 5.2.10 on 2026-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blogpost_blogpost_pub_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pillar',
            field=models.CharField(choices=[('networking', 'Wi-Fi & Networking'), ('security', 'Physical Security'), ('development', 'App & Web Development'), ('automation', 'Smart Home'), ('support', 'Support & Maintenance'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(choices=[('networking', 'Wi-Fi & Networking'), ('development', 'App & Web Development'), ('automation', 'Smart Home (install, setup or fix)'), ('support', 'Support & Maintenance'), ('other', 'Something else')], default='other', max_length=32),
        ),
    ]
