# Generated by Django 5.2.10 on 2026-09-30 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_retitle_construction_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='care_plan',
            field=models.CharField(blank=True, choices=[('', 'None / not decided'), ('essential', 'Essential'), ('professional', 'Professional'), ('concierge', 'Concierge')], db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='direct_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Direct delivery cost on the same VAT basis, including your labour allowance.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='installed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='internal_notes',
            field=models.TextField(blank=True, db_default=''),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='project_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed project revenue, excluding VAT.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='referral',
            field=models.CharField(blank=True, db_default='', help_text='Optional: Google, a neighbour, an electrician, an estate agent…', max_length=120, verbose_name='How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='review_requested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='stage',
            field=models.CharField(choices=[('new', 'New enquiry'), ('qualified', 'Qualified'), ('survey_booked', 'Survey booked'), ('survey_done', 'Survey completed'), ('quoted', 'Quote sent'), ('won', 'Quote accepted'), ('installed', 'Installation completed'), ('lost', 'Closed / not proceeding')], db_default='new', default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_campaign',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_medium',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_source',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='care_plan',
            field=models.CharField(blank=True, choices=[('', 'None / not decided'), ('essential', 'Essential'), ('professional', 'Professional'), ('concierge', 'Concierge')], db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='direct_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Direct delivery cost on the same VAT basis, including your labour allowance.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='installed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='internal_notes',
            field=models.TextField(blank=True, db_default=''),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='project_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed project revenue, excluding VAT.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='referral',
            field=models.CharField(blank=True, db_default='', help_text='Optional: Google, a neighbour, an electrician, an estate agent…', max_length=120, verbose_name='How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='review_requested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='stage',
            field=models.CharField(choices=[('new', 'New enquiry'), ('qualified', 'Qualified'), ('survey_booked', 'Survey booked'), ('survey_done', 'Survey completed'), ('quoted', 'Quote sent'), ('won', 'Quote accepted'), ('installed', 'Installation completed'), ('lost', 'Closed / not proceeding')], db_default='new', default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='utm_campaign',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='utm_medium',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='utm_source',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(choices=[('networking', 'Wi-Fi & Networking'), ('security', 'CCTV & Security'), ('development', 'App & Web Development'), ('automation', 'Smart Home (install, setup or fix)'), ('support', 'Support & Maintenance'), ('other', 'Something else')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='property_type',
            field=models.CharField(choices=[('home_unsure', 'Home — not sure of the size'), ('home_small', 'Home — under 150 m²'), ('home_medium', 'Home — 150–300 m²'), ('home_large', 'Home — 300 m² or larger'), ('home_period', 'Period or listed home'), ('home_estate', 'Estate or multi-building property'), ('business_office', 'Business — office'), ('business_retail', 'Business — retail / hospitality'), ('business_other', 'Business — something else'), ('construction_site', "Construction site / builder's compound"), ('new_build_dev', 'New-build development (one or more plots)'), ('other', 'Something else')], default='other', max_length=32),
        ),
    ]
