from django.urls import path

from . import api, views
from .feeds import BlogFeed

urlpatterns = [
    path("", views.home, name="home"),
    path("services/", views.services_overview, name="services"),
    path("services/networking/", views.service_networking, name="service_networking"),
    path("services/security/", views.service_security, name="service_security"),
    path("services/ai-cameras/", views.service_ai_cameras, name="service_ai_cameras"),
    path("our-approach-to-camera-privacy/", views.camera_privacy, name="camera_privacy"),
    path("services/development/", views.service_development, name="service_development"),
    path("services/automation/", views.service_automation, name="service_automation"),
    path("services/support/", views.service_support, name="service_support"),
    path("construction/", views.construction, name="construction"),
    path(
        "construction/capability-statement/",
        views.capability_statement,
        name="capability_statement",
    ),
    path("about/", views.about, name="about"),
    path("portfolio/", views.portfolio, name="portfolio"),
    path("portfolio/<slug:slug>/", views.case_study, name="case_study"),
    path("showcase/<slug:slug>/", views.showcase_demo, name="showcase_demo"),
    path("areas/", views.areas_index, name="areas"),
    path("areas/marlow/", views.area_marlow, name="area_marlow"),
    path("areas/maidenhead/", views.area_maidenhead, name="area_maidenhead"),
    path("areas/henley/", views.area_henley, name="area_henley"),
    path("areas/beaconsfield/", views.area_beaconsfield, name="area_beaconsfield"),
    path("contact/", views.contact, name="contact"),
    path("contact/thanks/", views.contact_thanks, name="contact_thanks"),
    path("quote/", views.quote, name="quote"),
    path("quote/thanks/", views.quote_thanks, name="quote_thanks"),
    path("careers/", views.careers, name="careers"),
    path("careers/thanks/", views.careers_thanks, name="careers_thanks"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy, name="privacy"),
    path("blog/", views.blog, name="blog"),
    path("blog/feed/", BlogFeed(), name="blog_feed"),
    path("blog/<slug:slug>/", views.blog_post, name="blog_post"),
    path("api/blog/posts/", api.posts_collection, name="api_blog_posts"),
    path("api/blog/posts/<slug:slug>/", api.post_detail, name="api_blog_post"),
    path("healthz", views.healthz, name="healthz"),
]
