"""BlogPost model behaviour: sanitisation, slugs, publishing manager."""
from datetime import timedelta

from django.test import TestCase
from django.utils import timezone

from core.models import BlogPost, QuoteRequest, sanitize_blog_html


class SanitizeHtmlTests(TestCase):
    def test_strips_script_and_event_handlers(self):
        dirty = '<p onclick="evil()">hi</p><script>steal()</script>'
        clean = sanitize_blog_html(dirty)
        self.assertNotIn("<script", clean)
        self.assertNotIn("steal()", clean)
        self.assertNotIn("onclick", clean)
        self.assertIn("<p>hi</p>", clean)

    def test_strips_javascript_url_but_keeps_relative(self):
        clean = sanitize_blog_html(
            '<a href="javascript:alert(1)">x</a>'
            '<a href="/services/networking/">ok</a>'
        )
        self.assertNotIn("javascript:", clean)
        self.assertIn("/services/networking/", clean)

    def test_keeps_blog_markup_and_relative_images(self):
        html = (
            '<h2>Heading</h2><figure>'
            '<img src="/static/img/blog/x.jpg" alt="x" loading="lazy" '
            'width="800" height="600"><figcaption>cap</figcaption></figure>'
            '<ul><li>one</li></ul>'
        )
        clean = sanitize_blog_html(html)
        self.assertIn("/static/img/blog/x.jpg", clean)
        self.assertIn('loading="lazy"', clean)
        self.assertIn("<figcaption>", clean)
        self.assertIn("<h2>", clean)

    def test_empty_is_safe(self):
        self.assertEqual(sanitize_blog_html(""), "")
        self.assertEqual(sanitize_blog_html(None), "")


class BlogPostSaveTests(TestCase):
    def test_save_sanitises_content(self):
        post = BlogPost.objects.create(
            title="Test Post",
            excerpt="x",
            content='<p>ok</p><script>bad()</script>',
        )
        post.refresh_from_db()
        self.assertNotIn("<script", post.content)
        self.assertIn("<p>ok</p>", post.content)

    def test_slug_autogenerated_from_title(self):
        post = BlogPost.objects.create(
            title="Why Wi-Fi Fails In Marlow", excerpt="x", content="<p>a</p>"
        )
        self.assertEqual(post.slug, "why-wi-fi-fails-in-marlow")

    def test_reading_time_minimum_one(self):
        post = BlogPost(title="t", excerpt="x", content="<p>one two three</p>")
        self.assertEqual(post.reading_time_minutes, 1)

    def test_seo_description_falls_back_to_excerpt(self):
        post = BlogPost(title="t", excerpt="An excerpt", content="x")
        self.assertEqual(post.seo_description, "An excerpt")
        post.meta_description = "A meta description"
        self.assertEqual(post.seo_description, "A meta description")


class PublishedManagerTests(TestCase):
    def setUp(self):
        BlogPost.objects.all().delete()
        now = timezone.now()
        self.live = BlogPost.objects.create(
            title="Live", excerpt="x", content="<p>a</p>",
            published_at=now - timedelta(days=1),
        )
        self.draft = BlogPost.objects.create(
            title="Draft", excerpt="x", content="<p>a</p>", published_at=None,
        )
        self.scheduled = BlogPost.objects.create(
            title="Scheduled", excerpt="x", content="<p>a</p>",
            published_at=now + timedelta(days=5),
        )

    def test_published_manager_excludes_drafts_and_future(self):
        published = list(BlogPost.published.all())
        self.assertIn(self.live, published)
        self.assertNotIn(self.draft, published)
        self.assertNotIn(self.scheduled, published)

    def test_is_published_flag(self):
        self.assertTrue(self.live.is_published)
        self.assertFalse(self.draft.is_published)
        self.assertFalse(self.scheduled.is_published)


class QuoteRequestTests(TestCase):
    def test_services_display_canonical_order(self):
        q = QuoteRequest(
            name="A", email="a@b.com", postcode="SL7 1AA",
            services="security,networking",
        )
        # Canonical order from QUOTE_SERVICE_CHOICES: networking before security.
        self.assertEqual(
            q.services_display(), "Wi-Fi & Networking, CCTV / Physical Security"
        )

    def test_services_display_empty(self):
        self.assertEqual(QuoteRequest(services="").services_display(), "")
